-- AlterTable
ALTER TABLE `Attendance` MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `Leaves` MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `Users` MODIFY `id` INTEGER NOT NULL AUTO_INCREMENT;
